### ISSUE TITLE
Invalid / missing "ProductVisibility" descriptions

### ISSUE THREAD

**Issue by am4rth** [shopware/admin-api-reference#139]
The schema for the `ProductVisibility"`has invalid descriptions for its fields. The description is always "Unique identity of product visibility."

![image](https://github.com/shopware/admin-api-reference/assets/96725262/25596830-3662-472a-8e75-330650628219)

Also it would be nice if there was a description or enum definition for the supported values of the `visibility` field.

**Comment by sushmangupta** [comment]
@am4rth , Thanks for bringing this up. It has been updated now. :) 

FYR : https://github.com/shopware/admin-api-reference/pull/148
