### ISSUE TITLE
Insufficient price api documentation

### ISSUE THREAD

**Issue by am4rth** [shopware/admin-api-reference#253]
The current documentation of the admin api is lacking some information regarding price resources. The openapi definition contains a invalid documentation for `price` property of the `Product` and `ProductPrice` resource.  Following the openapi docs the property should be a `object` but that is not correct. As stated in https://shopware.stoplight.io/docs/admin-api/e51cf55ab14a4-product-management#price the price property should be a array of objects.

We were unable to find a defintion of this "price object". The "Product Managment" page of the docs hints to some properties (`gross`,`net`,`linked`) but not all (`listPrice`, `regulationPrice`).

By inspecting the requests made from the Admin UI we were able to "reverse engineer" the information needed. Please correct me if i am wrong, but this is what we got:

The `product.price`, `product.purchasePrice`, `product.prices[].price` properties all require/accept a array as value. The array elements must be of a object with the following openapi defintion:

```json
// #/components/schemas/Price
      "Price": {
        "required": [
          "currencyId",
          "gross",
          "net",
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[0-9a-f]{32}$",
            "description": "Unique identity of the product's price."
          },
          "currencyId": {
            "type": "string",
            "pattern": "^[0-9a-f]{32}$"
          },
          "gross": {
            "type": "number",
            "format": "double",
            "example": 13.37
          },
          "net": {
            "type": "number",
            "format": "double",
            "example": 11.24
          },
          "linked": {
            "type": "boolean",
            "example": false,
            "description": "Links gross and net price together?"
          },
          "listPrice": {
            "type": "object",
            "required": [
              "gross",
              "net",
            ],
            "properties": {
              "gross": {
                "type": "number",
                "format": "double"
              },
              "net": {
                "type": "number",
                "format": "double"
              },
              "linked": {
                "type": "boolean",
              }
            }
          },
          "regulationPrice": {
            "type": "object",
            "required": [
              "gross",
              "net",
            ],
            "properties": {
              "gross": {
                "type": "number",
                "format": "double"
              },
              "net": {
                "type": "number",
                "format": "double"
              },
              "linked": {
                "type": "boolean",
              }
            }
          }
        }
      },


```

It would be a better Developer Experince if the openapi defintion for the Admin API would state the expected properties for the price objects. Theses objects are used at multiple endpoints/resources so it's kinda weird that this essential information is not given directly were it's needed. It also would be very nice if the openapi defintion schemas would contain example values and/or descriptions for some properties (e.g. linked).

**Comment by bojanrajh** [comment]
Fixed in https://github.com/shopware/shopware/commit/181404c8d8039cd400f08dc97beb6eed65aea503, dumped to Stoplight in https://github.com/shopware/admin-api-reference/pull/281.
