### ISSUE TITLE
Incorrect response for detailed customer with MIME-type application/json

### ISSUE THREAD

**Issue by zUniQueX** [shopware/admin-api-reference#32]
## Shopware version
6.5.3.3

## Problem
When requesting the `/customer/{id}` endpoint with a header `Accept: application/json`, the response contains one `data` field which itself contains the `Customer` object. The OpenAPI spec describes the schema to return a `Customer` object directly.

**Comment by zUniQueX** [comment]
The same behaviour can be observed when requesting e.g. `/order/{id}`

**Comment by sushmangupta** [comment]
@zUniQueX , Thanks for reporting this issue. We see that there is an issue with schema generation. This has been reported to the team and a[ ticket ](https://shopware.atlassian.net/browse/NEXT-29460) has been raised.
I shall update you once it's fixed. 👍

**Comment by Isengo1989** [comment]
Closed with 

https://github.com/shopware/shopware/commit/7ca43a754b4e741c0c0a0b91cf6dd007ffb0bf09
