### ISSUE TITLE
Some arrays are defined as objects instead

### ISSUE THREAD

**Issue by flowl** [shopware/admin-api-reference#41]
Looking at this docs page: https://shopware.stoplight.io/docs/admin-api/935c55fbf5072-product-data

The field `price` is an array of objects:

```
"price": [
    {
      "currencyId": "b7d2554b0ce847cd82f3ac9bd1c0dfca",
      "gross": 15,
      "net": 10,
      "linked": false
    }
  ],
```

But on this page of the docs (in the schema?), `price` is defined as a single object (pick `application/json`):

https://shopware.stoplight.io/docs/admin-api/1c10c832ff905-create-a-new-product-resources

    price: object

It's very confusing which types to pick with wrong types in the schema. Especially with useless error messages that don't indicate which field is malformed:

        {
            "status": "400",
            "code": "FRAMEWORK__WRITE_MALFORMED_INPUT",
            "title": "Bad Request",
            "detail": "Expected data to be array.",
            "meta": {
                "parameters": []
            },

Example of failing product with above error message:

```
{
	"productNumber": "123456789",
	"stock": 940,
	"price": [{
		"net": 512.5,
		"gross": 615,
		"linked": true,
		"currencyId": "b7d2554b0ce847cd82f3ac9bd1c0dfca"
	}],
	"taxId": "0189d4cafd527d4387b5747bffdb3439",
	"manufacturer": {
		"name": "Garmin"
	},
	"manufacturerNumber": null,
	"children": [],
	"active": true,
	"shippingFree": false,
	"ean": "",
	"minPurchase": 1,
	"maxPurchase": null,
	"purchaseUnit": null,
	"weight": 0,
	"width": 0,
	"height": 0,
	"length": 0,
	"packUnit": null,
	"deliveryTime": null,
	"name": "Sapphire",
	"keywords": null,
	"metaDescription": null,
	"metaTitle": null,
	"description": "",
	"releaseDate": null,
	"updatedAt": "2023-05-25 11:02:11",
	"createdAt": "2021-09-09 17:27:23"
}
```

**Please fix the types in the schema and make the Exception more verbose, containing the field that is malformed.**

**Comment by Isengo1989** [comment]
@flowl thank you for raising the issue. Sadly we can not adapt the schema in this repo, since it is autogenerated by code. I will pass it on tho and leave the ticket open till then.

**Comment by Isengo1989** [comment]
Closed due to duplicate: https://github.com/shopware/platform/issues/3255
