### ISSUE TITLE
`configuratorGroupConfig` missing in Product definition

### ISSUE THREAD

**Issue by flowl** [shopware/admin-api-reference#43]
Go to https://shopware.stoplight.io/docs/admin-api/1c10c832ff905-create-a-new-product-resources (pick `application/json` in doubt).

There is no field `configuratorGroupConfig` like listed on this page: https://shopware.stoplight.io/docs/admin-api/935c55fbf5072-product-data

**Comment by Isengo1989** [comment]
@flowl thank your for the issue.

This was fixed in this [PR](https://github.com/shopware/admin-api-reference/pull/51) 

The config you are looking for is `variantListingConfig`, here is an example:

```
"variantListingConfig": {
    "displayParent": false,
    "mainVariantId": null,
    "configuratorGroupConfig": [
      {
        "id": "269c7e40a54a462e884edb004c5f7bc8",
        "representation": "box",
        "expressionForListings": true
      }
    ]
  }
```
